refector : boardFormPageController 관련 service,entity logic,naming변경 #112
playdata-finalproject/teamproject_final pull request #113
Opened 2021-06-12 06:19 UTC by jeeseungbae

2021-06-12 11:35 UTC, hyojaekim requested changes
앞으로 적용하면 좋을 것 같은 내용에 대해서 언급하자면 아래와 같아요!

1. Junit에는 어떤 메서드가 있고, 어떻게 활용할 것인가?
2. 현재 서비스에 있는 메서드에는 하는 일이 많은 경우가 있는데 이부분에 대해서는 어떻게 리팩토링을 할 것인가?

(점차 발전하는 모습이 보기 좋아요! ㅎㅎ)

2021-06-12 11:35 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
> +        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
아래 링크를 참고해서 디미터의 법칙에 대해서 알아보고 적용해보면 좋을 것 같아요!

https://woowacourse.github.io/javable/post/2020-06-02-law-of-demeter/

2021-06-12 11:35 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
>          Board board1 = Board.builder()
board1 이라는 이름을 사용한 이유가 있을까요?!

2021-06-12 11:35 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/business/service/logic/CategoryLogicService.java
> +                .orElseThrow(NoSuchElementException::new);
좋아용 👍🏻
커스텀 예외를 만들어보면 더 좋을 것 같다는 생각이 들어요!
예외를 커스텀으로 만들면 의미를 더 명확하게 만들 수 있어요 ㅎ

2021-06-12 11:35 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/domain/repository/BoardRepository.java
> +    Page<Board> findBoardByCategoryIdAndTitleContainingAndContentsContainingOrderByRegisteredAtDescIdDesc(Long id,String title,String content,Pageable pageable);
해당 메서드는 복잡하다는 생각이 들어요!
다른 사람이 봤을 때, 해당 메서드가 어떤 일을 수행하는지 파악하기 어려울 것 같아요.
직접 쿼리를 작성하는 것이 더 낫지 않을까요?!

2021-06-12 11:35 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/domain/repository/BoardRepository.java
>      List<Board> findTop5ByCategoryIdAndRegisteredAtBetweenOrderByViewBoardDesc(Long id, LocalDate date1, LocalDate date2);
여기도 마찬가지에요! ㅎ

2021-06-12 11:35 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/domain/repository/CategoryRepository.java
> +@Transactional
인터페이스에 @Transactional을 사용한 이유가 있을까요?!

해당 어노테이션은 우선순위가 존재하는데 이 부분을 고려했는지 궁금합니다! 🤔

2021-06-12 11:35 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/presentation/controller/view/board/BoardFormPageController.java
> +    @Autowired
@Autowired 어노테이션을 사용한 이유가 있을까요?
(필드로 의존성을 주입받는 경우는 @Autowired는 생략이 가능해요 😄)

그리고 외부에서 주입 받는 방식에는 필드, 생성자, setter로 3가지 방식이 있어요!
이 부분에 대해서 나만의 기준을 만들어서 어떻게 주입받을지 고민해보면 좋을 것 같아요! 😄

2021-06-12 11:35 UTC, hyojaekim commented on app/src/test/java/com/finalproject/shelter/domain/repository/CategoryRepositoryTest.java
> +    public void findById(){
인텔리제이에서 자동 포맷팅 기능을 활용해보면 좋을 것 같아요! 😄

2021-06-12 11:35 UTC, hyojaekim commented on app/src/test/java/com/finalproject/shelter/domain/repository/CategoryRepositoryTest.java
> +            System.out.println(select);
해당 테스트에서 검증하는 로직이 없는 것 같아요!

이외에도 System.out.println를 사용하는 것은 지양하는 것을 권장할게요! ㅎㅎ
왜 지양하는지 이 부분에 대해서는 고민해보시면 좋을 것 같아요! 😄

2021-06-12 11:35 UTC, hyojaekim commented on app/src/test/java/com/finalproject/shelter/domain/repository/CategorytableRepositoryTest.java
> +        categorytable.ifPresent(System.out::println);
이 부분도 마찬가지에요! 검증하는 로직이 없어요 ㅠㅠ
 
그리고 System으로 print를 찍는 것은 지양하는 것을 권장합니다! 😄

2021-06-12 11:35 UTC, hyojaekim commented on app/src/test/java/com/finalproject/shelter/presentation/controller/BoardViewPageControllerTest.java
> +//    @DisplayName("view 페이지 조회 확인 테스트")
주석으로 처리된 코드는 삭제하는 것이 좋지 않을까요?! 😄

2021-06-13 08:17 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
> +        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
네 감사합니다!

2021-06-13 08:17 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
>          Board board1 = Board.builder()
없습니다. 객체명 교체하겠습니다.

2021-06-14 06:03 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
>          Board board1 = Board.builder()
한꺼번에 많은것을 수정하기가 어려워서 계층별로 나눠서 Controller -> service -> model 순으로 리팩토링할 예정입니다. board1 이름을 사용한 이유는 없고 이후 service에서 리팩토링 때 진행하겠습니다!

2021-06-14 06:14 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/business/service/logic/CategoryLogicService.java
> +                .orElseThrow(NoSuchElementException::new);
감사합니다~~~

2021-06-14 06:20 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/domain/repository/BoardRepository.java
> +    Page<Board> findBoardByCategoryIdAndTitleContainingAndContentsContainingOrderByRegisteredAtDescIdDesc(Long id,String title,String content,Pageable pageable);
맞습니다!!하지만 한꺼번에 많은것을 수정하기가 어려워서 계층별로 나눠서 Controller -> service -> model 순으로 리팩토링 할 예정입니다. 빠른 시일내에 수정하겠습니다!

2021-06-14 06:21 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/domain/repository/BoardRepository.java
>      List<Board> findTop5ByCategoryIdAndRegisteredAtBetweenOrderByViewBoardDesc(Long id, LocalDate date1, LocalDate date2);
네 감사합니다!!

2021-06-14 06:27 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/domain/repository/CategoryRepository.java
> +@Transactional
트랜잭션을 이용하여 오류나 에러상태를 감지하여 오류상태일시 DB에 반영하지 못하도록 하려고 사용하였습니다. 
어노테이션의 우선순위에 대해 공부하여 적용시키겠습니다!!

2021-06-14 06:48 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/presentation/controller/view/board/BoardFormPageController.java
> +    @Autowired
아... 감사합니다 공부해서 적용하겠습니다!

2021-06-14 08:52 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/presentation/controller/view/board/BoardFormPageController.java
> +    @Autowired
생성자로 의존성을 주입받는 경우를 말씀하시는 건가요???

알려주시는 방법들을 다시 공부한 덕분에 조금의 차이점을 알게되었습니다!! 감사합니다!!

2021-06-14 09:05 UTC, jeeseungbae commented on app/src/test/java/com/finalproject/shelter/domain/repository/CategoryRepositoryTest.java
> +    public void findById(){
아아!! 감사합니다~~

2021-06-14 09:15 UTC, jeeseungbae commented on app/src/test/java/com/finalproject/shelter/domain/repository/CategoryRepositoryTest.java
> +            System.out.println(select);
감사합니다!! 수정하겠습니다.
System.out.println을 사용하게 되면 수많은 테스트과정에서 한번더 확인해야하는 번거로움이 있는 것 같은데 그 밖에도 다른 이유가 있을까요???

2021-06-14 09:15 UTC, jeeseungbae commented on app/src/test/java/com/finalproject/shelter/domain/repository/CategorytableRepositoryTest.java
> +        categorytable.ifPresent(System.out::println);
감사합니다!!!

2021-06-14 09:18 UTC, jeeseungbae commented on app/src/test/java/com/finalproject/shelter/presentation/controller/BoardViewPageControllerTest.java
> +//    @DisplayName("view 페이지 조회 확인 테스트")
코드 수정중 에러가 발생하여 잠시 주석처리 해놨습니다ㅜㅜ 빠른시일내에 복구하겠습니다.

2021-06-14 12:45 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/domain/repository/CategoryRepository.java
> +@Transactional
좋아용ㅎㅎ 그리고 트랜잭션에 대해서 아래와 같은 부분을 학습해보면 좋을거 같아요! 👍🏻

1. 트랜잭션의 특징 및 성질
2. 어떻게 동작하는가?
3. 해당 어노테이션은 어떤 옵션이 있고, 어떤 경우에 사용해야 할까?

2021-06-14 12:46 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/presentation/controller/view/board/BoardFormPageController.java
> +    @Autowired
넵! 조금씩 알아가면서 나만의 기준을 만들면 좋겠네요! ㅎㅎ👍🏻

2021-06-14 12:56 UTC, hyojaekim commented on app/src/test/java/com/finalproject/shelter/domain/repository/CategoryRepositoryTest.java
> +            System.out.println(select);
다른 테스트는 Assertions에 있는 메서드로 검증을 하고 있는데
해당 테스트는 System.out.println 뿐이에요!
만약에 여기서 테스트가 실패한다면 어떻게 검증할 수 있을까요?!

현재는 테스트 코드라 크게 상관없겠지만
특히 System.out.println은 실제 운영 코드에는 사용하지 않는 것을 권장할게요!
해당 코드는 개발 환경에서 사용하는 코드이고, 실제 운영하고 있는 서비스에는 필요없는 코드라서
성능에 영향을 미칠 수가 있어요!

2021-06-14 13:04 UTC, hyojaekim approved these changes
점점 발전하는 모습이 좋아용 👍🏻
일단은 approve할게요!

2021-06-14 13:04 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
> +            selectboard.setNickname(board.getUser()
다음번에는 setter를 사용하지 않도록 리팩토링 해보면 좋을 것 같아요 ㅎㅎ

2021-06-14 13:04 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/presentation/controller/view/board/BoardViewPageController.java
> +    private final AnswerLogicService answerLogicService;
👍🏻👍🏻👍🏻

2021-06-14 13:04 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/presentation/controller/view/board/BoardViewPageController.java
> +        model.addAttribute("monthview", boardLogicService.bestmonthview(getCategoryId(eachBoard)));
model.addAttribute에서 많은 내용을 담고 있는데
해당 데이터를 담고 있는 객체를 생성하는 것은 어떨까요?!

2021-06-14 13:59 UTC, jeeseungbae commented on app/src/test/java/com/finalproject/shelter/domain/repository/CategoryRepositoryTest.java
> +            System.out.println(select);
아~~ 더 많은 정보 주셔서 감사합니다!!

2021-06-14 14:02 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
> +            selectboard.setNickname(board.getUser()
여러개의 방법으로 하는 것이 좋아서 그런건가요??? 
아니면 저기에서 setter를 사용할 때 문제점이라도 있나요???

2021-06-14 14:04 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/presentation/controller/view/board/BoardViewPageController.java
> +        model.addAttribute("monthview", boardLogicService.bestmonthview(getCategoryId(eachBoard)));
오!!! 정말 좋은 방법인것 같습니다!! 
가독성이 훨씬 늘어날것 같아요!!!
좋은정보 감사합니다~

2021-06-14 14:29 UTC, jeeseungbae commented
오 정말 좋은 정보 감사합니다!!!
하지만 현재 코드 리팩토링 후 REST API를 더 고려해볼 생각이라 model.addAtrribut에 많은 내용이 담길지 모르겠습니다. 추후 더 진행할 때 꼭 고려해보겠습니다.

2021-06-14 14:31 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/domain/repository/CategoryRepository.java
> +@Transactional
오 더 좋은 학습방법 감사합니다!!

2021-06-14 14:33 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/presentation/controller/view/board/BoardViewPageController.java
> +        model.addAttribute("monthview", boardLogicService.bestmonthview(getCategoryId(eachBoard)));
오 정말 좋은 정보 감사합니다!!!
하지만 현재 코드 리팩토링 후 REST API를 더 고려해볼 생각이라 model.addAtrribut에 많은 내용이 담길지 모르겠습니다. 추후 더 진행할 때 꼭 고려해보겠습니다.

2021-06-14 14:35 UTC, merged

2021-06-15 12:25 UTC, hyojaekim commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
> +            selectboard.setNickname(board.getUser()
객체는 독립적이어야 해요!

외부에서 상태를 조작할 수 있다는 것은
해당 객체의 상태를 외부로부터 노출 시키는 것이 아닐까요?
객체에게 메시지를 보내는 것은 어떨까요?

정답은 없으니 이 부분에 대해서 고민해보고,
그리고 캡슐화에 대해서도 알아보면 좋을 것 같네용! 😄

2021-07-07 10:28 UTC, jeeseungbae commented on app/src/main/java/com/finalproject/shelter/business/service/logic/BoardLogicService.java
> +            selectboard.setNickname(board.getUser()
네 감사합니다.